### ISSUE TITLE
Using this to install cassandra

### ISSUE THREAD

**Issue by reznet** [saltstack-formulas/sun-java-formula#15]
Has anyone had success using this formula and then installing cassandra?  I've been trying to install both sun's java and cassandra 2.2.4 using salt, and am using the cassandra formula at  https://github.com/whisklabs/salt-cassandra-formula.  I'm able to run this formula, and verify that when I log in, I can run java, but when the cassandra formula runs, the package fails with the error:  Cassandra 2.0 and later require Java 7u25 or later.  However, I can sudo run cassandra in standalone mode.  but I can't start the cassandra service.

http://stackoverflow.com/questions/24190063/cassandra-2-complaining-about-java-7-when-i-have-java-7-installed suggests that perhaps the java formula needs to call set-alternatives --set in addition to calling --install in order to make java available to root.

Does that sound right, or does anyone have a better way to install cassandra with salt on an ubuntu 14 box?

**Comment by sroegner** [comment]
The error message from cassandra leaves lots of room for speculation - let's assume their start script picks the first java executable in the system PATH and uses that - the java version of that is by design not going to be the one installed by sun-java-formula. Changing the default alternative of the java binary for the system as suggested in the so article you link to is quite heavy-handed and therefore not something the formula would do.

The cassandra formula appears to have no way of using a custom JAVA_HOME but does offer an option to install the right JRE for you - you'd have to set a pillar (or grain) looking like this before you run salt again and you would probably not need sun-java-formula at all:

```
cassandra:
    install_java: True
```

hth and good luck!
Steffen

**Comment by vutny** [comment]
@reznet I think this issue could be closed.

**Comment by seglo** [comment]
I'm using this formula to do the same thing (run version 3.4 of Cassandra).

The formula does indeed install java 8, but for whatever reason it's not in the PATH when root (or is it the cassandra user?) attempts to start the start the service.

Cassandra was able to start after I manually called `update-alternatives` to set my default JVM globally in the path.

```
sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/java/bin/java" 1
sudo update-alternatives --set java /usr/lib/java/bin/java
```

At this point in time I'm not sure how to make this happen with `sun-java`, but the `yum` Cassandra install requires that `java` be in the default PATH to run.  

Would this warrant an update to the formula  @sroegner or @vutny ?  Any suggestions would be welcome.

**Comment by gravyboat** [comment]
The cassandra-formula repo should probably just be created at some point, using this java formula for getting Cassandra set up seems to be common, but has problems.

**Comment by sroegner** [comment]
@seglo the updates to sun-java-formula you are suggesting are both to work around shortcomings of the cassandra formula - I would really think the changes are to be made on the cassandra side. Sorry

**Comment by vutny** [comment]
@seglo Sorry for the late answer.
Probably we could introduce configurable java alternative in the similar way as we do in `create-java-home` state. That's would be useful, I guess.

Thoughts?

**Comment by seglo** [comment]
@vutny No worries.  Your suggestion sounds fine to me.  I think it would be a worthwhile feature given how many salt practitioners would use this formula when managing JVM services.

**Comment by noelmcloughlin** [comment]
https://github.com/saltstack-formulas/sun-java-formula/pull/32
